var $jscomp={scope:{},findInternal:function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6-impl","es3");
var path="https://pay.freshhopesystems.com/",school_key="timest_",MY=function(){this.makeUse=function(a,b,c,d){d=void 0===d?null:d;$.ajax({url:path+a,type:"POST",data:b,cache:!1,processData:!1,contentType:!1,dataType:"JSON",success:function(a){c(a)},error:function(a,b,c){d(a,b,c)}})};this.load=function(a){swal({title:'<div class="preloader-wrapper small active"><div class="spinner-layer spinner-red-only"><div class="circle-clipper left"><div class="circle"></div></div><div class="gap-patch"><div class="circle"></div></div><div class="circle-clipper right"><div class="circle"></div></div></div></div>',text:void 0===
a?null:a,html:!0,showConfirmButton:!1})};this.onBackKeyDown=function(a){a.preventDefault();confirm("Are you sure you want to exit this app")?navigator.app.exitApp():alert("Enjoy yourself!")};this.offline=function(){$(".all-page-box").html("No internet connection!")};this.online=function(){$("li[my-page=student]").trigger("click")}},my=new MY;document.addEventListener("backbutton",my.onBackKeyDown,!1);document.addEventListener("offline",my.offline,!1);document.addEventListener("online",my.online,!1);
var networkState=navigator.connection.type;networkState!==Connection.NONE&&$(".all-page-box").html("No internet connection!");
function payWithPaystack(a,b,c,d){PaystackPop.setup({key:"pk_test_627b3212869ed34b3c5dee07082de6ece430cd6a",email:b,amount:c,ref:""+Math.floor(1E9*Math.random()+1),metadata:{custom_fields:[{display_name:"Fullname",variable_name:"name",value:a}]},callback:function(a){$.ajax({url:path+"user/payment.html",type:"POST",data:$("body").find(".pay").serialize()+"&school_key="+school_key+"&ref_code="+a.reference,cache:!1,dataType:"JSON",success:function(b){"error"!=b.status?swal({title:"Successful",text:"<b>You reference code is "+
a.reference+"</b>",html:!0,type:"success",confirmButtonClass:"btn btn-wine"},function(){window.location=""}):swal({title:"",text:"<h5>"+b.text+"</h5>",html:!0,type:"warning",confirmButtonClass:"btn btn-danger"})},error:function(a,b,c){swal({title:"",text:"Something went wrong",html:!0,type:"warning",confirmButtonClass:"btn btn-danger"})}})},onClose:function(){$(".pay_load").html("")}}).openIframe()}
Number.prototype.formatMoney=function(a,b,c){var d=this;a=isNaN(a=Math.abs(a))?2:a;b=void 0==b?".":b;c=void 0==c?",":c;var e=0>d?"-":"",f=String(parseInt(d=Math.abs(Number(d)||0).toFixed(a))),g=3<(g=f.length)?g%3:0;return e+(g?f.substr(0,g)+c:"")+f.substr(g).replace(/(\d{3})(?=\d)/g,"$1"+c)+(a?b+Math.abs(d-f).toFixed(a).slice(2):"")};$(".button-collapse").sideNav({edge:"left",closeOnClick:!0,draggable:!0});
$(".register-form").validate({highlight:function(a){$(a).closest(".form-group").addClass("has-error")},unhighlight:function(a){$(a).closest(".form-group").removeClass("has-error")},errorElement:"span",errorClass:"help-block",errorPlacement:function(a,b){b.parent(".input-group").length?a.insertAfter(b.parent()):a.insertAfter(b)},submitHandler:function(a){my.load("Processing...");a=new FormData(a);a.append("school_key",school_key);my.makeUse("user/register.html",a,function(a){"error"!=a.status?(swal({title:"<h4>"+
a.text+"</h4>",text:"",html:!0,type:"success",confirmButtonClass:"btn btn-success"}),$(".parent-input").val(a.iid),$(".register-form").trigger("reset"),$(".pick-second").trigger("click"),localStorage.setItem("logg",!0),localStorage.setItem("user_details",JSON.stringify(a.user_details))):swal({title:"",text:"<h5>"+a.text+"</h5>",html:!0,type:"warning",confirmButtonClass:"btn btn-danger"})},function(a,c,d){swal({title:"",text:"Something went wrong",html:!0,type:"warning",confirmButtonClass:"btn btn-danger"})});
return!1}});
$(".login-form").validate({highlight:function(a){$(a).closest(".form-group").addClass("has-error")},unhighlight:function(a){$(a).closest(".form-group").removeClass("has-error")},errorElement:"span",errorClass:"help-block",errorPlacement:function(a,b){b.parent(".input-group").length?a.insertAfter(b.parent()):a.insertAfter(b)},submitHandler:function(a){my.load("Processing...");a=new FormData(a);a.append("school_key",school_key);my.makeUse("user/login.html",a,function(a){"error"!=a.status?(localStorage.setItem("logg",
!0),localStorage.setItem("user_details",JSON.stringify(a.text)),window.location="data/index.html"):swal({title:"",text:"<h5>"+a.text+"</h5>",html:!0,type:"warning",confirmButtonClass:"btn btn-danger"})},function(a,c,d){swal({title:"",text:"Something went wrong",html:!0,type:"warning",confirmButtonClass:"btn btn-danger"})});return!1}});
function add_student(a){a=void 0===a?!0:a;$("body").find(".student-form").validate({highlight:function(a){$(a).closest(".form-group").addClass("has-error")},unhighlight:function(a){$(a).closest(".form-group").removeClass("has-error")},errorElement:"span",errorClass:"help-block",errorPlacement:function(a,c){c.parent(".input-group").length?a.insertAfter(c.parent()):a.insertAfter(c)},submitHandler:function(b){my.load("Processing...");b=new FormData(b);b.append("school_key",school_key);my.makeUse("user/add-student.html",
b,function(b){"error"!=b.status?swal({title:"",text:"<h5>"+b.text+"</h5>",html:!0,type:"success",confirmButtonClass:"btn btn-success"},function(){$(".student-form").trigger("reset");1==a&&(window.location="data/index.html")}):swal({title:"",text:"<h5>"+b.text+"</h5>",html:!0,type:"warning",confirmButtonClass:"btn btn-danger"})},function(a,b,e){swal({title:"",text:"Something went wrong",html:!0,type:"warning",confirmButtonClass:"btn btn-danger"})});return!1}})}add_student();
function my_account(){var a=JSON.parse(localStorage.getItem("user_details"));$("body").find(".firstname").html('<i class="ti-user"></i> Firstname: '+a.firstname);$("body").find(".lastname").html('<i class="ti-user"></i> Lastname: '+a.lastname);$("body").find(".email").html('<i class="ti-inbox"></i> '+a.email)}
$("body").on("click",".rl",function(){$(".all-page-box").html('<div class="col-md-12"><div class="preloader-wrapper small active"><div class="spinner-layer spinner-red-only"><div class="circle-clipper left"><div class="circle"></div></div><div class="gap-patch"><div class="circle"></div></div><div class="circle-clipper right"><div class="circle"></div></div></div></div></div>');if(null!=localStorage.getItem("user_details"))var a=JSON.parse(localStorage.getItem("user_details"));var b=$(this).attr("my-page"),
c=$(this).attr("my-class"),d=$(this).attr("my-fullname");$(".all-page-box").load(b+".html",function(){swal.close();$(".rl").sideNav("hide");"class"===b?$.post(path+"user/get_s_class.html",{school_key:school_key,class_name:c},function(b,f,g){f="<tr><th>Type</th><th>Amount</th></tr>";g="Class fee;PTA;Graduation Fee;School Event;Day Care;After School;Sportswear - Wednesday;Friday".split(";");var e=0;$(".class_name").html("Class name: "+b.class_name);$(".student_name").html("Student: "+d);$("input[name=name]").val(a.firstname+
" "+a.lastname);$("input[name=email]").val(a.email);$("input[name=parent_id]").val(a.id);$("input[name=class_name]").val(c);$("input[name=student_name]").val(d);for(var h in b)if(e<g.length){if("id"!=h||"class_name"!=h)f+="<tr><th>"+g[e]+"</th><td>"+b[h]+'</td><td><input type="checkbox" class="fee_type" data-v="'+b[h]+'" name="'+h+'" value="'+g[e]+'"></td></tr>';e++}$(".getclassinfo").html(f);$("body").on("submit",".pay",function(){my.load("Loading payment form...");var a=$(this).find("#name").val(),
b=$(this).find("#email").val(),c=$(this).find("#amount").val()+"00",d=new FormData($(this));payWithPaystack(a,b,c,d);return!1})},"json"):"account"===b?my_account():"student"===b?list_student():"add-student"===b&&($(".parent-input").val(a.id),add_student(!1))})});$("body").on("click","input[class=fee_type]",function(){var a=0;$(this).is(":checked");$("input[class=fee_type]:checked").each(function(){a+=parseInt($(this).attr("data-v"))});$(".total_to_pay").html("N"+a.formatMoney(2,".",","));$("input[name=amount]").val(a)});
var gClass;function lc(a){var b,c;for(c in a){var d=a[c];b+='<option value="'+d.class_name+'">'+d.class_name+"</option>"}return b}$.post(path+"user/list-class.html",{school_key:school_key},function(a,b,c){gClass=a},"json");
function list_student(){if(null!=localStorage.getItem("user_details")){my.load("Loading students...");var a=JSON.parse(localStorage.getItem("user_details"));$.post(path+"user/get-student.html",{school_key:school_key,id:a.id},function(a,c,d){if(""!=a){$("body").find(".short-note").html("You have "+a.length+" students");c='<p class="my-panel-heading"> All students </p>';for(var b in a)d=a[b],c+='<p my-fullname="'+d.fullname+'" my-class="'+d["class"]+'" my-page="class" class="rl waves-effect my-panel-body list-group-item"><span><b>Full name: '+
d.fullname+"</b></span><br><span>Class: "+d["class"]+"</span></p>";swal.close()}else c='<br><br><center><h4>No student !</h4><p><button my-page="add-student" class="rl btn btn-wine">Add students</button></p></center><br><br>';$("body").find(".list-student").html(c)},"json")}}list_student();
$("body").on("change",".student-number",function(){for(var a=$(this).val(),b="",c=0;c<a;c++)b+="<p>Student "+(c+1)+'</p><div class="form-group"><input type="text" name="fullname[]" class="form-control" placeholder="Student full name" required="required"></div><div class="form-group"><select name="class[]" class="form-control" required="required"><option value="">Select class</option>'+lc(gClass)+"</select></div>";$(".students-form-fields").html(b)});
$(".logout").on("click",function(){localStorage.removeItem("logg");localStorage.removeItem("user_details");window.location="../index.html"});
